spring.application.name=dateplan-api
server.port=${PORT:8080}

server.forward-headers-strategy=framework

spring.config.import=optional:file:../../.env[.properties]

spring.jpa.hibernate.ddl-auto=validate
spring.data.redis.url=${REDIS_URL}

spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=10000

spring.jpa.open-in-view=false

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${SECRET}
jwt.issuer=${ISSUER}
jwt.audience=${AUDIENCE}

password.salt.length=${SALT_LENGTH}
password.hash.length=${HASH_LENGTH}
password.parallelism=${PARALLELISM}
password.memory=${MEMORY}
password.iterations=${ITERATIONS}

firebase.json.path=${FIREBASE_JSON_PATH}
