name: teste

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: configurar jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: gerar o build jar
        run: ./gradlew bootjar

      - name: disponibilizar o jar
        uses: actions/upload-artifact@v7
        with:
          name: Jar
          path: build/libs/dateplan-api-0.0.1-SNAPSHOT.jar
  


